Dev
urospetrovic34/zadatak2-bonus pull request #1
Opened 2021-09-15 07:18 UTC by urospetrovic34

2021-09-15 07:44 UTC, sbozic85 requested changes
Urose lepo je sto koristis CSS Grid ali vidi da sredis par stvari:
1. Ja gledam na laptopu gde je ekran sirine nesto vise od 1200px i dobijam mobilnu verziju gde su elementi svi jedan ispod drugog. Gledaj da skaliras onaj desktop dizajn da se lepo vidi i na toj velicini
2. Obrati paznju na ovaj deo iz style guidea:

- Note for text colors:
- 1. "Verified Graduate" has the same color as the person's name with 50% opacity
- 2. Review paragraphs inside the quotations have the same color as well, but are at 70% opacity

Cini mi se da nisi nista od toga primenio. Npr. boja #a3a3a3 se ne spominje u style guide
3. Dobio si favicon u resursima pa ubaci i to
4. Proveri jos jednom responsive. Treba da izgleda dobro na ekranima od 320px pa navise

2021-09-15 10:29 UTC, urospetrovic34 commented
Stavio sam da elementi idu jedan ispod drugog na 768px, odnosno od tablet uređaja pa na manje

2021-09-16 14:54 UTC, chomii82 requested changes
1. Bilo bi lepo da nazivi klasa budu na engleskom
2. Vidi da na velikim ekranima das maksimalnu sirinu kontejneru. Pogledaj jos jednom dizajn.
3. Lepo je sto si primetio da elementi imaju box-shadow ali je ovaj tvoj suvise jak. Malo to doteraj.
4. Pogledaj koje slike po dizajnu imaju border pa i to izmeni.
5. Pogledaj breakpointe oko 768px i 992px posto bi i tu trebalo da se prikazuje lepo.
![image_2021_09_16T14_52_27_024Z](https://user-images.githubusercontent.com/90196420/133634842-048e27e9-e3b2-47f2-8c9c-aee7d2fbd7d9.png)
![image_2021_09_16T14_53_28_900Z](https://user-images.githubusercontent.com/90196420/133634899-d6a9fba2-f909-47dd-bfa8-06c90f8148c8.png)

2021-09-17 07:50 UTC, sbozic85 approved these changes

2021-09-17 07:50 UTC, merged